# Generated by Django 4.2.7 on 2023-11-06 10:14

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_image_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/images', validators=[shop.validators.validate_file_size]),
        ),
    ]
